export type EventCategory = 'speed-dating' | 'singles-party' | 'virtual' | 'outdoor' | 'workshop' | 'concert' | 'food-drink';

export interface DateEvent {
  id: string;
  title: string;
  category: EventCategory;
  emoji: string;
  description: string;
  date: Date;
  endDate: Date;
  location: string;
  city: string;
  isVirtual: boolean;
  price: number;
  originalPrice?: number;
  maxAttendees: number;
  currentAttendees: number;
  tags: string[];
  color: string;
  hostName: string;
  hostEmoji: string;
  ageRange: string;
  gender: 'all' | 'women-only' | 'men-only' | 'lgbtq+';
  badge?: string;
}

const now = Date.now();
const d = (days: number, hour = 19, min = 0) =>
  new Date(now + days * 86400000 + (hour - new Date().getHours()) * 3600000 - new Date().getMinutes() * 60000 + min * 60000);

export const events: DateEvent[] = [
  {
    id: 'ev-sd-berlin-1',
    title: 'Speed Dating Berlin – Mitte Night',
    category: 'speed-dating',
    emoji: '💘',
    description:
      'Join 30+ singles for a fast-paced evening of 5-minute dates in the heart of Berlin Mitte. Enjoy complimentary welcome drinks, structured mini-dates, and a free-mixing after-party. Our friendly host keeps the energy high and the awkward silences short.',
    date: d(2, 19, 30),
    endDate: d(2, 22, 0),
    location: 'Soho House Berlin, Torstraße 1, Mitte',
    city: 'Berlin',
    isVirtual: false,
    price: 18,
    maxAttendees: 30,
    currentAttendees: 24,
    tags: ['speed-dating', 'drinks', 'ages 25–35', 'mixed'],
    color: 'from-pink-600 to-rose-500',
    hostName: 'Lisa M.',
    hostEmoji: '👩‍🦰',
    ageRange: '25–35',
    gender: 'all',
    badge: 'Almost Full',
  },
  {
    id: 'ev-sd-munich-1',
    title: 'Munich Speed Dating – English Edition',
    category: 'speed-dating',
    emoji: '🍻',
    description:
      'An English-language speed dating evening designed for internationals living in Munich. 20 participants, 10 dates per person, all wrapped up in under 2 hours. Beer garden vibes optional afterwards.',
    date: d(5, 19, 0),
    endDate: d(5, 21, 30),
    location: 'Bar Centrale, Leopoldstr. 46, Schwabing',
    city: 'Munich',
    isVirtual: false,
    price: 15,
    maxAttendees: 20,
    currentAttendees: 20,
    tags: ['speed-dating', 'english', 'international', 'beer'],
    color: 'from-amber-500 to-orange-500',
    hostName: 'James T.',
    hostEmoji: '🧔',
    ageRange: '27–40',
    gender: 'all',
    badge: 'Sold Out',
  },
  {
    id: 'ev-sd-hamburg-1',
    title: 'Hamburg Speed Dating – Harbour Vibes',
    category: 'speed-dating',
    emoji: '⚓',
    description:
      'Meet fellow singles aboard a private harbour-side venue in Hamburg. 25 participants, stunning water views, and a curated playlist. Our host ensures the whole evening flows smoothly from icebreakers to the final match reveal.',
    date: d(9, 20, 0),
    endDate: d(9, 22, 30),
    location: 'Clouds Heaven\'s Bar, Reeperbahn 1',
    city: 'Hamburg',
    isVirtual: false,
    price: 20,
    maxAttendees: 25,
    currentAttendees: 17,
    tags: ['speed-dating', 'harbour', 'cocktails', 'premium'],
    color: 'from-blue-600 to-cyan-500',
    hostName: 'Sarah K.',
    hostEmoji: '👩‍🎤',
    ageRange: '28–42',
    gender: 'all',
  },
  {
    id: 'ev-party-berlin-1',
    title: 'Berlin Singles Party – Summer Edition',
    category: 'singles-party',
    emoji: '🎉',
    description:
      'The city\'s biggest singles party returns for summer! DJ sets, themed cocktails, icebreaker games, and a chill rooftop area. Over 100 singles aged 22–38. Doors open at 9 PM, peak hours 10 PM–1 AM.',
    date: d(3, 21, 0),
    endDate: d(4, 2, 0),
    location: 'Watergate Club, Falckensteinstr. 49, Kreuzberg',
    city: 'Berlin',
    isVirtual: false,
    price: 12,
    maxAttendees: 120,
    currentAttendees: 98,
    tags: ['party', 'DJ', 'rooftop', 'summer', 'nightlife'],
    color: 'from-purple-600 to-pink-500',
    hostName: 'Aura Events',
    hostEmoji: '🎊',
    ageRange: '22–38',
    gender: 'all',
    badge: 'Almost Full',
  },
  {
    id: 'ev-party-cologne-1',
    title: 'Cologne Singles Night – Old Town',
    category: 'singles-party',
    emoji: '🍸',
    description:
      'A sophisticated singles evening in Cologne\'s charming old town. Great cocktails, curated background music, and a relaxed atmosphere perfect for meeting new people. Ideal for those who prefer mingling over structured formats.',
    date: d(12, 20, 0),
    endDate: d(12, 24, 0),
    location: 'Bar Malin, Hohe Straße 12, Altstadt',
    city: 'Cologne',
    isVirtual: false,
    price: 10,
    maxAttendees: 60,
    currentAttendees: 31,
    tags: ['cocktails', 'old-town', 'casual', 'mingling'],
    color: 'from-emerald-500 to-teal-500',
    hostName: 'Kevin P.',
    hostEmoji: '🧑‍💼',
    ageRange: '24–36',
    gender: 'all',
  },
  {
    id: 'ev-virtual-1',
    title: 'Virtual Coffee Dating – Sunday Chill',
    category: 'virtual',
    emoji: '☕',
    description:
      'No travel needed! Join our cozy virtual speed-dating session over Zoom. We rotate pairs every 6 minutes for a total of 8 mini-dates. All you need is a coffee (or your drink of choice) and good Wi-Fi.',
    date: d(1, 11, 0),
    endDate: d(1, 13, 0),
    location: 'Online (Zoom)',
    city: 'Online',
    isVirtual: true,
    price: 0,
    maxAttendees: 40,
    currentAttendees: 22,
    tags: ['free', 'virtual', 'coffee', 'casual', 'zoom'],
    color: 'from-sky-500 to-indigo-500',
    hostName: 'Mia R.',
    hostEmoji: '👩‍💻',
    ageRange: '22–40',
    gender: 'all',
    badge: 'Free',
  },
  {
    id: 'ev-virtual-2',
    title: 'LGBTQ+ Virtual Mixer',
    category: 'virtual',
    emoji: '🏳️‍🌈',
    description:
      'A welcoming and inclusive virtual mixer for LGBTQ+ singles. Relaxed group chat, breakout rooms for 1:1 conversations, and optional icebreaker prompts. A safe space to meet people from anywhere in Germany.',
    date: d(7, 18, 0),
    endDate: d(7, 20, 0),
    location: 'Online (Zoom)',
    city: 'Online',
    isVirtual: true,
    price: 0,
    maxAttendees: 50,
    currentAttendees: 29,
    tags: ['lgbtq+', 'free', 'inclusive', 'virtual', 'mixer'],
    color: 'from-violet-500 to-fuchsia-500',
    hostName: 'Alex F.',
    hostEmoji: '🧑‍🎨',
    ageRange: 'All ages',
    gender: 'lgbtq+',
    badge: 'Free',
  },
  {
    id: 'ev-outdoor-berlin-1',
    title: 'Berlin Singles Hiking – Grunewald',
    category: 'outdoor',
    emoji: '🌲',
    description:
      'Lace up your boots and join 20 singles for a 10 km hike through the Grunewald forest. Beautiful trails, great conversation, and a post-hike picnic with snacks included. No dating experience required, just comfy shoes!',
    date: d(4, 10, 0),
    endDate: d(4, 14, 30),
    location: 'Grunewald Forest, S-Bahn Grunewald entrance',
    city: 'Berlin',
    isVirtual: false,
    price: 8,
    originalPrice: 12,
    maxAttendees: 20,
    currentAttendees: 14,
    tags: ['hiking', 'nature', 'outdoors', 'active', 'picnic'],
    color: 'from-green-600 to-emerald-500',
    hostName: 'Tom W.',
    hostEmoji: '🧗',
    ageRange: '23–40',
    gender: 'all',
  },
  {
    id: 'ev-outdoor-frankfurt-1',
    title: 'Frankfurt Singles Walk – Sachsenhausen',
    category: 'outdoor',
    emoji: '🏙️',
    description:
      'A guided stroll through Frankfurt\'s scenic Sachsenhausen neighbourhood. We stop at 3 landmarks with icebreaker activities at each. End the evening at a local Apfelwein pub – drink not included.',
    date: d(14, 17, 0),
    endDate: d(14, 20, 0),
    location: 'Schweizer Platz, Sachsenhausen, Frankfurt',
    city: 'Frankfurt',
    isVirtual: false,
    price: 5,
    maxAttendees: 25,
    currentAttendees: 9,
    tags: ['walk', 'city', 'scenic', 'casual', 'apfelwein'],
    color: 'from-lime-500 to-green-500',
    hostName: 'Nina S.',
    hostEmoji: '👩‍🌾',
    ageRange: '25–45',
    gender: 'all',
    badge: 'New',
  },
  {
    id: 'ev-workshop-munich-1',
    title: 'Wine Tasting for Singles – Munich',
    category: 'workshop',
    emoji: '🍷',
    description:
      'An elegant evening of guided wine tasting for singles in Munich. A certified sommelier leads you through 6 wines from across Europe, with matched cheese and charcuterie boards. Mingle over shared tasting notes and great conversation.',
    date: d(8, 18, 30),
    endDate: d(8, 21, 30),
    location: 'Weinhaus Neuner, Herzogspitalstr. 8, Munich',
    city: 'Munich',
    isVirtual: false,
    price: 35,
    maxAttendees: 18,
    currentAttendees: 13,
    tags: ['wine', 'tasting', 'sophisticated', 'gourmet', 'cheese'],
    color: 'from-rose-600 to-red-500',
    hostName: 'Pierre L.',
    hostEmoji: '🧑‍🍳',
    ageRange: '28–50',
    gender: 'all',
  },
  {
    id: 'ev-concert-hamburg-1',
    title: 'Concert Singles Meetup – Hamburg Jazz',
    category: 'concert',
    emoji: '🎷',
    description:
      'A curated jazz concert evening for music-loving singles. We attend together as a group, grab drinks at the venue bar, and chat during the break. Perfect for people who connect over culture. Ticket to the concert is included.',
    date: d(11, 19, 0),
    endDate: d(11, 23, 0),
    location: 'Fabrik Hamburg, Barnerstraße 36',
    city: 'Hamburg',
    isVirtual: false,
    price: 25,
    maxAttendees: 30,
    currentAttendees: 19,
    tags: ['jazz', 'concert', 'music', 'culture', 'drinks'],
    color: 'from-yellow-500 to-amber-500',
    hostName: 'Marcus D.',
    hostEmoji: '🎶',
    ageRange: '26–45',
    gender: 'all',
  },
  {
    id: 'ev-food-berlin-1',
    title: 'Singles Cooking Class – Italian Night',
    category: 'food-drink',
    emoji: '🍝',
    description:
      'Learn to cook authentic Italian pasta and tiramisu alongside 12 other singles. A professional chef guides you through each step while you get to know your cooking partner. Dinner is served – and so are the sparks! All ingredients and aprons provided.',
    date: d(18, 18, 30),
    endDate: d(18, 21, 30),
    location: 'Cucina Urbana, Prenzlauer Berg, Berlin',
    city: 'Berlin',
    isVirtual: false,
    price: 45,
    originalPrice: 60,
    maxAttendees: 14,
    currentAttendees: 10,
    tags: ['cooking', 'italian', 'pasta', 'hands-on', 'dinner'],
    color: 'from-orange-600 to-red-500',
    hostName: 'Chef Marco',
    hostEmoji: '👨‍🍳',
    ageRange: '24–42',
    gender: 'all',
  },
];
