// Live Gifts Catalog — Discordium dating-app livestream feature
// Modelled after TikTok / Bigo Live gift systems.

export type GiftTier = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
export type GiftAnimationType = 'toast' | 'burst' | 'spin' | 'explosion' | 'fullscreen' | 'legendary';
export type GiftCategory =
  | 'love'
  | 'fantasy'
  | 'animals'
  | 'luxury'
  | 'music'
  | 'food'
  | 'nature'
  | 'gaming'
  | 'special';

export interface Gift {
  id: string;
  name: string;
  emoji: string;
  coinCost: number;
  tier: GiftTier;
  category: GiftCategory;
  animationType: GiftAnimationType;
  color: string;
  rarity: string;
}

// ---------------------------------------------------------------------------
// TIER META
// ---------------------------------------------------------------------------

export const TIER_META: Record<
  GiftTier,
  {
    label: string;
    color: string;   // text-xxx
    bg: string;      // bg-xxx/20
    border: string;  // border-xxx/30
    glow: string;    // bg-xxx/10
  }
> = {
  common: {
    label: 'Common',
    color: 'text-slate-400',
    bg: 'bg-slate-400/20',
    border: 'border-slate-400/30',
    glow: 'bg-slate-400/10',
  },
  uncommon: {
    label: 'Uncommon',
    color: 'text-green-400',
    bg: 'bg-green-400/20',
    border: 'border-green-400/30',
    glow: 'bg-green-400/10',
  },
  rare: {
    label: 'Rare',
    color: 'text-blue-400',
    bg: 'bg-blue-400/20',
    border: 'border-blue-400/30',
    glow: 'bg-blue-400/10',
  },
  epic: {
    label: 'Epic',
    color: 'text-purple-400',
    bg: 'bg-purple-400/20',
    border: 'border-purple-400/30',
    glow: 'bg-purple-400/10',
  },
  legendary: {
    label: 'Legendary',
    color: 'text-amber-400',
    bg: 'bg-amber-400/20',
    border: 'border-amber-400/30',
    glow: 'bg-amber-400/10',
  },
};

// ---------------------------------------------------------------------------
// CATEGORY META
// ---------------------------------------------------------------------------

export const GIFT_CATEGORIES: Array<{ id: GiftCategory; label: string; emoji: string }> = [
  { id: 'love',    label: 'Love',    emoji: '💖' },
  { id: 'fantasy', label: 'Fantasy', emoji: '🧙' },
  { id: 'animals', label: 'Animals', emoji: '🐾' },
  { id: 'luxury',  label: 'Luxury',  emoji: '💎' },
  { id: 'music',   label: 'Music',   emoji: '🎵' },
  { id: 'food',    label: 'Food',    emoji: '🍓' },
  { id: 'nature',  label: 'Nature',  emoji: '🌿' },
  { id: 'gaming',  label: 'Gaming',  emoji: '🎮' },
  { id: 'special', label: 'Special', emoji: '✨' },
];

// ---------------------------------------------------------------------------
// FULL GIFT CATALOG
// ---------------------------------------------------------------------------

export const GIFTS: Gift[] = [
  // =========================================================================
  // LOVE — 22 gifts
  // =========================================================================

  // common
  {
    id: 'love_001',
    name: 'Rose',
    emoji: '🌹',
    coinCost: 1,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-rose-400 to-pink-500',
    rarity: 'common',
  },
  {
    id: 'love_002',
    name: 'Heart',
    emoji: '❤️',
    coinCost: 5,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-red-400 to-rose-500',
    rarity: 'common',
  },
  {
    id: 'love_003',
    name: 'Kiss',
    emoji: '💋',
    coinCost: 15,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-pink-400 to-fuchsia-500',
    rarity: 'common',
  },
  {
    id: 'love_004',
    name: 'Teddy Bear',
    emoji: '🧸',
    coinCost: 20,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-amber-300 to-orange-400',
    rarity: 'common',
  },
  {
    id: 'love_005',
    name: 'Love Letter',
    emoji: '💌',
    coinCost: 30,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-pink-300 to-rose-400',
    rarity: 'common',
  },
  {
    id: 'love_006',
    name: 'Couple',
    emoji: '👫',
    coinCost: 45,
    tier: 'common',
    category: 'love',
    animationType: 'toast',
    color: 'from-rose-300 to-pink-400',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'love_007',
    name: 'Bouquet',
    emoji: '💐',
    coinCost: 50,
    tier: 'uncommon',
    category: 'love',
    animationType: 'burst',
    color: 'from-pink-400 to-purple-500',
    rarity: 'uncommon',
  },
  {
    id: 'love_008',
    name: 'Heart Balloon',
    emoji: '🎈',
    coinCost: 75,
    tier: 'uncommon',
    category: 'love',
    animationType: 'burst',
    color: 'from-red-400 to-pink-500',
    rarity: 'uncommon',
  },
  {
    id: 'love_009',
    name: 'Sparkling Heart',
    emoji: '💖',
    coinCost: 100,
    tier: 'uncommon',
    category: 'love',
    animationType: 'burst',
    color: 'from-pink-500 to-rose-600',
    rarity: 'uncommon',
  },
  {
    id: 'love_010',
    name: 'Chocolate Box',
    emoji: '🍫',
    coinCost: 150,
    tier: 'uncommon',
    category: 'love',
    animationType: 'burst',
    color: 'from-amber-600 to-brown-700',
    rarity: 'uncommon',
  },
  {
    id: 'love_011',
    name: 'Cupid Arrow',
    emoji: '💘',
    coinCost: 200,
    tier: 'uncommon',
    category: 'love',
    animationType: 'burst',
    color: 'from-red-400 to-pink-600',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'love_012',
    name: 'Ring',
    emoji: '💍',
    coinCost: 300,
    tier: 'rare',
    category: 'love',
    animationType: 'spin',
    color: 'from-yellow-300 to-amber-500',
    rarity: 'rare',
  },
  {
    id: 'love_013',
    name: 'Heart Crown',
    emoji: '👑',
    coinCost: 500,
    tier: 'rare',
    category: 'love',
    animationType: 'spin',
    color: 'from-rose-400 to-pink-600',
    rarity: 'rare',
  },
  {
    id: 'love_014',
    name: 'Love Potion',
    emoji: '🧪',
    coinCost: 800,
    tier: 'rare',
    category: 'love',
    animationType: 'spin',
    color: 'from-fuchsia-400 to-pink-600',
    rarity: 'rare',
  },
  {
    id: 'love_015',
    name: 'Forever Rose',
    emoji: '🌹✨',
    coinCost: 1200,
    tier: 'rare',
    category: 'love',
    animationType: 'spin',
    color: 'from-red-500 to-rose-700',
    rarity: 'rare',
  },

  // epic
  {
    id: 'love_016',
    name: 'Diamond Ring',
    emoji: '💍💎',
    coinCost: 2000,
    tier: 'epic',
    category: 'love',
    animationType: 'explosion',
    color: 'from-cyan-400 to-blue-600',
    rarity: 'epic',
  },
  {
    id: 'love_017',
    name: 'Love Throne',
    emoji: '❤️👑',
    coinCost: 3500,
    tier: 'epic',
    category: 'love',
    animationType: 'explosion',
    color: 'from-red-500 to-purple-700',
    rarity: 'epic',
  },
  {
    id: 'love_018',
    name: 'Heart Universe',
    emoji: '💗🌌',
    coinCost: 6000,
    tier: 'epic',
    category: 'love',
    animationType: 'explosion',
    color: 'from-pink-500 to-indigo-700',
    rarity: 'epic',
  },
  {
    id: 'love_019',
    name: 'Proposal',
    emoji: '💍🥂',
    coinCost: 8000,
    tier: 'epic',
    category: 'love',
    animationType: 'explosion',
    color: 'from-yellow-400 to-pink-600',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'love_020',
    name: 'Wedding',
    emoji: '💒👰🤵',
    coinCost: 10000,
    tier: 'legendary',
    category: 'love',
    animationType: 'fullscreen',
    color: 'from-white via-pink-200 to-rose-500',
    rarity: 'legendary',
  },
  {
    id: 'love_021',
    name: 'Soulmates',
    emoji: '✨💑✨',
    coinCost: 25000,
    tier: 'legendary',
    category: 'love',
    animationType: 'legendary',
    color: 'from-rose-400 via-fuchsia-500 to-violet-600',
    rarity: 'legendary',
  },
  {
    id: 'love_022',
    name: 'Eternal Love',
    emoji: '♾️💖🌹',
    coinCost: 50000,
    tier: 'legendary',
    category: 'love',
    animationType: 'legendary',
    color: 'from-red-500 via-pink-500 to-purple-600',
    rarity: 'legendary',
  },

  // =========================================================================
  // FANTASY — 18 gifts
  // =========================================================================

  // common
  {
    id: 'fantasy_001',
    name: 'Fairy Dust',
    emoji: '🧚',
    coinCost: 10,
    tier: 'common',
    category: 'fantasy',
    animationType: 'toast',
    color: 'from-violet-300 to-purple-400',
    rarity: 'common',
  },
  {
    id: 'fantasy_002',
    name: 'Magic Wand',
    emoji: '🪄',
    coinCost: 20,
    tier: 'common',
    category: 'fantasy',
    animationType: 'toast',
    color: 'from-indigo-300 to-violet-400',
    rarity: 'common',
  },
  {
    id: 'fantasy_003',
    name: 'Crystal Ball',
    emoji: '🔮',
    coinCost: 35,
    tier: 'common',
    category: 'fantasy',
    animationType: 'toast',
    color: 'from-purple-400 to-blue-500',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'fantasy_004',
    name: 'Wizard Hat',
    emoji: '🧙',
    coinCost: 60,
    tier: 'uncommon',
    category: 'fantasy',
    animationType: 'burst',
    color: 'from-indigo-400 to-purple-600',
    rarity: 'uncommon',
  },
  {
    id: 'fantasy_005',
    name: 'Elf',
    emoji: '🧝',
    coinCost: 90,
    tier: 'uncommon',
    category: 'fantasy',
    animationType: 'burst',
    color: 'from-green-400 to-emerald-600',
    rarity: 'uncommon',
  },
  {
    id: 'fantasy_006',
    name: 'Mermaid',
    emoji: '🧜',
    coinCost: 180,
    tier: 'uncommon',
    category: 'fantasy',
    animationType: 'burst',
    color: 'from-cyan-400 to-teal-600',
    rarity: 'uncommon',
  },
  {
    id: 'fantasy_007',
    name: 'Spell Book',
    emoji: '📖✨',
    coinCost: 250,
    tier: 'uncommon',
    category: 'fantasy',
    animationType: 'burst',
    color: 'from-violet-400 to-indigo-600',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'fantasy_008',
    name: 'Unicorn',
    emoji: '🦄',
    coinCost: 500,
    tier: 'rare',
    category: 'fantasy',
    animationType: 'spin',
    color: 'from-pink-400 via-violet-400 to-blue-400',
    rarity: 'rare',
  },
  {
    id: 'fantasy_009',
    name: 'Enchanted Sword',
    emoji: '⚔️🔮',
    coinCost: 700,
    tier: 'rare',
    category: 'fantasy',
    animationType: 'spin',
    color: 'from-blue-400 to-indigo-600',
    rarity: 'rare',
  },
  {
    id: 'fantasy_010',
    name: 'Griffin',
    emoji: '🦅🦁',
    coinCost: 1200,
    tier: 'rare',
    category: 'fantasy',
    animationType: 'spin',
    color: 'from-amber-400 to-yellow-600',
    rarity: 'rare',
  },
  {
    id: 'fantasy_011',
    name: 'Potion Chest',
    emoji: '🧪💰',
    coinCost: 1800,
    tier: 'rare',
    category: 'fantasy',
    animationType: 'spin',
    color: 'from-green-400 to-teal-600',
    rarity: 'rare',
  },

  // epic
  {
    id: 'fantasy_012',
    name: 'Dragon',
    emoji: '🐉',
    coinCost: 3000,
    tier: 'epic',
    category: 'fantasy',
    animationType: 'explosion',
    color: 'from-red-500 to-orange-700',
    rarity: 'epic',
  },
  {
    id: 'fantasy_013',
    name: 'Dark Wizard',
    emoji: '🧙‍♂️⚡',
    coinCost: 5000,
    tier: 'epic',
    category: 'fantasy',
    animationType: 'explosion',
    color: 'from-violet-600 to-slate-900',
    rarity: 'epic',
  },
  {
    id: 'fantasy_014',
    name: 'Dragon Rider',
    emoji: '🐉🤺',
    coinCost: 8500,
    tier: 'epic',
    category: 'fantasy',
    animationType: 'explosion',
    color: 'from-orange-500 to-red-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'fantasy_015',
    name: 'Phoenix',
    emoji: '🔥🦅🔥',
    coinCost: 15000,
    tier: 'legendary',
    category: 'fantasy',
    animationType: 'fullscreen',
    color: 'from-orange-400 via-red-500 to-yellow-300',
    rarity: 'legendary',
  },
  {
    id: 'fantasy_016',
    name: 'Celestial Dragon',
    emoji: '🐲✨🌌',
    coinCost: 30000,
    tier: 'legendary',
    category: 'fantasy',
    animationType: 'legendary',
    color: 'from-cyan-400 via-violet-500 to-purple-700',
    rarity: 'legendary',
  },
  {
    id: 'fantasy_017',
    name: 'Realm of Gods',
    emoji: '⚡🏛️👑',
    coinCost: 75000,
    tier: 'legendary',
    category: 'fantasy',
    animationType: 'legendary',
    color: 'from-yellow-300 via-amber-400 to-orange-600',
    rarity: 'legendary',
  },
  {
    id: 'fantasy_018',
    name: 'Creation Myth',
    emoji: '🌌🌍✨🔮',
    coinCost: 99999,
    tier: 'legendary',
    category: 'fantasy',
    animationType: 'legendary',
    color: 'from-indigo-500 via-purple-500 to-pink-500',
    rarity: 'legendary',
  },

  // =========================================================================
  // ANIMALS — 18 gifts
  // =========================================================================

  // common
  {
    id: 'animals_001',
    name: 'Butterfly',
    emoji: '🦋',
    coinCost: 8,
    tier: 'common',
    category: 'animals',
    animationType: 'toast',
    color: 'from-violet-300 to-purple-400',
    rarity: 'common',
  },
  {
    id: 'animals_002',
    name: 'Bunny',
    emoji: '🐰',
    coinCost: 12,
    tier: 'common',
    category: 'animals',
    animationType: 'toast',
    color: 'from-pink-200 to-rose-300',
    rarity: 'common',
  },
  {
    id: 'animals_003',
    name: 'Panda',
    emoji: '🐼',
    coinCost: 25,
    tier: 'common',
    category: 'animals',
    animationType: 'toast',
    color: 'from-slate-300 to-slate-500',
    rarity: 'common',
  },
  {
    id: 'animals_004',
    name: 'Kitten',
    emoji: '🐱',
    coinCost: 18,
    tier: 'common',
    category: 'animals',
    animationType: 'toast',
    color: 'from-amber-200 to-orange-300',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'animals_005',
    name: 'Fox',
    emoji: '🦊',
    coinCost: 55,
    tier: 'uncommon',
    category: 'animals',
    animationType: 'burst',
    color: 'from-orange-400 to-red-500',
    rarity: 'uncommon',
  },
  {
    id: 'animals_006',
    name: 'Peacock',
    emoji: '🦚',
    coinCost: 110,
    tier: 'uncommon',
    category: 'animals',
    animationType: 'burst',
    color: 'from-teal-400 to-green-600',
    rarity: 'uncommon',
  },
  {
    id: 'animals_007',
    name: 'Flamingo',
    emoji: '🦩',
    coinCost: 160,
    tier: 'uncommon',
    category: 'animals',
    animationType: 'burst',
    color: 'from-pink-400 to-rose-600',
    rarity: 'uncommon',
  },
  {
    id: 'animals_008',
    name: 'Wolf',
    emoji: '🐺',
    coinCost: 240,
    tier: 'uncommon',
    category: 'animals',
    animationType: 'burst',
    color: 'from-slate-400 to-blue-600',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'animals_009',
    name: 'Lion',
    emoji: '🦁',
    coinCost: 1000,
    tier: 'rare',
    category: 'animals',
    animationType: 'spin',
    color: 'from-yellow-400 to-amber-600',
    rarity: 'rare',
  },
  {
    id: 'animals_010',
    name: 'Elephant',
    emoji: '🐘',
    coinCost: 650,
    tier: 'rare',
    category: 'animals',
    animationType: 'spin',
    color: 'from-slate-400 to-slate-600',
    rarity: 'rare',
  },
  {
    id: 'animals_011',
    name: 'Golden Eagle',
    emoji: '🦅',
    coinCost: 900,
    tier: 'rare',
    category: 'animals',
    animationType: 'spin',
    color: 'from-yellow-400 to-amber-700',
    rarity: 'rare',
  },
  {
    id: 'animals_012',
    name: 'Snow Leopard',
    emoji: '🐆❄️',
    coinCost: 1600,
    tier: 'rare',
    category: 'animals',
    animationType: 'spin',
    color: 'from-slate-200 to-cyan-400',
    rarity: 'rare',
  },

  // epic
  {
    id: 'animals_013',
    name: 'Tiger',
    emoji: '🐅',
    coinCost: 4000,
    tier: 'epic',
    category: 'animals',
    animationType: 'explosion',
    color: 'from-orange-500 to-amber-700',
    rarity: 'epic',
  },
  {
    id: 'animals_014',
    name: 'White Tiger',
    emoji: '🐅✨',
    coinCost: 6500,
    tier: 'epic',
    category: 'animals',
    animationType: 'explosion',
    color: 'from-white to-blue-300',
    rarity: 'epic',
  },
  {
    id: 'animals_015',
    name: 'Orca',
    emoji: '🐋🌊',
    coinCost: 9000,
    tier: 'epic',
    category: 'animals',
    animationType: 'explosion',
    color: 'from-slate-800 to-blue-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'animals_016',
    name: 'Spirit Wolf',
    emoji: '🐺🌕✨',
    coinCost: 12000,
    tier: 'legendary',
    category: 'animals',
    animationType: 'fullscreen',
    color: 'from-slate-600 via-blue-500 to-indigo-700',
    rarity: 'legendary',
  },
  {
    id: 'animals_017',
    name: 'Leviathan',
    emoji: '🐉🌊🌊',
    coinCost: 40000,
    tier: 'legendary',
    category: 'animals',
    animationType: 'legendary',
    color: 'from-teal-600 via-cyan-500 to-blue-800',
    rarity: 'legendary',
  },
  {
    id: 'animals_018',
    name: 'God of Beasts',
    emoji: '🦁🌟🐉',
    coinCost: 88888,
    tier: 'legendary',
    category: 'animals',
    animationType: 'legendary',
    color: 'from-amber-400 via-orange-500 to-red-700',
    rarity: 'legendary',
  },

  // =========================================================================
  // LUXURY — 18 gifts
  // =========================================================================

  // common
  {
    id: 'luxury_001',
    name: 'Coin',
    emoji: '🪙',
    coinCost: 5,
    tier: 'common',
    category: 'luxury',
    animationType: 'toast',
    color: 'from-yellow-300 to-amber-400',
    rarity: 'common',
  },
  {
    id: 'luxury_002',
    name: 'Gem',
    emoji: '💠',
    coinCost: 20,
    tier: 'common',
    category: 'luxury',
    animationType: 'toast',
    color: 'from-cyan-300 to-blue-400',
    rarity: 'common',
  },
  {
    id: 'luxury_003',
    name: 'Watch',
    emoji: '⌚',
    coinCost: 40,
    tier: 'common',
    category: 'luxury',
    animationType: 'toast',
    color: 'from-slate-400 to-slate-600',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'luxury_004',
    name: 'Gold Bar',
    emoji: '🏅',
    coinCost: 80,
    tier: 'uncommon',
    category: 'luxury',
    animationType: 'burst',
    color: 'from-yellow-400 to-amber-600',
    rarity: 'uncommon',
  },
  {
    id: 'luxury_005',
    name: 'Diamond',
    emoji: '💎',
    coinCost: 175,
    tier: 'uncommon',
    category: 'luxury',
    animationType: 'burst',
    color: 'from-cyan-300 to-blue-500',
    rarity: 'uncommon',
  },
  {
    id: 'luxury_006',
    name: 'Briefcase',
    emoji: '💼',
    coinCost: 280,
    tier: 'uncommon',
    category: 'luxury',
    animationType: 'burst',
    color: 'from-amber-700 to-stone-800',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'luxury_007',
    name: 'Luxury Bag',
    emoji: '👜💎',
    coinCost: 400,
    tier: 'rare',
    category: 'luxury',
    animationType: 'spin',
    color: 'from-amber-500 to-yellow-700',
    rarity: 'rare',
  },
  {
    id: 'luxury_008',
    name: 'Penthouse',
    emoji: '🏙️',
    coinCost: 800,
    tier: 'rare',
    category: 'luxury',
    animationType: 'spin',
    color: 'from-slate-500 to-blue-700',
    rarity: 'rare',
  },
  {
    id: 'luxury_009',
    name: 'Mansion',
    emoji: '🏰',
    coinCost: 1500,
    tier: 'rare',
    category: 'luxury',
    animationType: 'spin',
    color: 'from-stone-400 to-amber-600',
    rarity: 'rare',
  },

  // epic
  {
    id: 'luxury_010',
    name: 'Sports Car',
    emoji: '🏎️',
    coinCost: 5000,
    tier: 'epic',
    category: 'luxury',
    animationType: 'explosion',
    color: 'from-red-500 to-orange-600',
    rarity: 'epic',
  },
  {
    id: 'luxury_011',
    name: 'Helicopter',
    emoji: '🚁',
    coinCost: 7500,
    tier: 'epic',
    category: 'luxury',
    animationType: 'explosion',
    color: 'from-slate-500 to-blue-600',
    rarity: 'epic',
  },
  {
    id: 'luxury_012',
    name: 'Supercar',
    emoji: '🏎️💨',
    coinCost: 9500,
    tier: 'epic',
    category: 'luxury',
    animationType: 'explosion',
    color: 'from-yellow-400 to-amber-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'luxury_013',
    name: 'Yacht',
    emoji: '🛥️🌊',
    coinCost: 20000,
    tier: 'legendary',
    category: 'luxury',
    animationType: 'fullscreen',
    color: 'from-blue-400 via-cyan-500 to-teal-600',
    rarity: 'legendary',
  },
  {
    id: 'luxury_014',
    name: 'Private Jet',
    emoji: '✈️💎',
    coinCost: 50000,
    tier: 'legendary',
    category: 'luxury',
    animationType: 'legendary',
    color: 'from-slate-400 via-blue-500 to-indigo-700',
    rarity: 'legendary',
  },
  {
    id: 'luxury_015',
    name: 'Island',
    emoji: '🏝️🌴💰',
    coinCost: 80000,
    tier: 'legendary',
    category: 'luxury',
    animationType: 'legendary',
    color: 'from-emerald-400 via-teal-500 to-cyan-600',
    rarity: 'legendary',
  },
  {
    id: 'luxury_016',
    name: 'Space Station',
    emoji: '🛸🌍💎',
    coinCost: 99999,
    tier: 'legendary',
    category: 'luxury',
    animationType: 'legendary',
    color: 'from-indigo-600 via-blue-700 to-slate-900',
    rarity: 'legendary',
  },
  // extra common/uncommon for variety
  {
    id: 'luxury_017',
    name: 'Pearl',
    emoji: '🫧',
    coinCost: 15,
    tier: 'common',
    category: 'luxury',
    animationType: 'toast',
    color: 'from-blue-100 to-slate-200',
    rarity: 'common',
  },
  {
    id: 'luxury_018',
    name: 'Vintage Wine',
    emoji: '🍷✨',
    coinCost: 120,
    tier: 'uncommon',
    category: 'luxury',
    animationType: 'burst',
    color: 'from-red-600 to-purple-700',
    rarity: 'uncommon',
  },

  // =========================================================================
  // MUSIC — 18 gifts
  // =========================================================================

  // common
  {
    id: 'music_001',
    name: 'Music Note',
    emoji: '🎵',
    coinCost: 3,
    tier: 'common',
    category: 'music',
    animationType: 'toast',
    color: 'from-violet-300 to-purple-400',
    rarity: 'common',
  },
  {
    id: 'music_002',
    name: 'Headphones',
    emoji: '🎧',
    coinCost: 14,
    tier: 'common',
    category: 'music',
    animationType: 'toast',
    color: 'from-slate-400 to-slate-600',
    rarity: 'common',
  },
  {
    id: 'music_003',
    name: 'Microphone',
    emoji: '🎤',
    coinCost: 22,
    tier: 'common',
    category: 'music',
    animationType: 'toast',
    color: 'from-gray-400 to-gray-600',
    rarity: 'common',
  },
  {
    id: 'music_004',
    name: 'Vinyl Record',
    emoji: '💿',
    coinCost: 38,
    tier: 'common',
    category: 'music',
    animationType: 'toast',
    color: 'from-slate-600 to-gray-800',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'music_005',
    name: 'Guitar',
    emoji: '🎸',
    coinCost: 100,
    tier: 'uncommon',
    category: 'music',
    animationType: 'burst',
    color: 'from-amber-500 to-orange-600',
    rarity: 'uncommon',
  },
  {
    id: 'music_006',
    name: 'Saxophone',
    emoji: '🎷',
    coinCost: 130,
    tier: 'uncommon',
    category: 'music',
    animationType: 'burst',
    color: 'from-yellow-400 to-amber-600',
    rarity: 'uncommon',
  },
  {
    id: 'music_007',
    name: 'Drum Kit',
    emoji: '🥁',
    coinCost: 200,
    tier: 'uncommon',
    category: 'music',
    animationType: 'burst',
    color: 'from-red-400 to-orange-500',
    rarity: 'uncommon',
  },
  {
    id: 'music_008',
    name: 'Trumpet',
    emoji: '🎺',
    coinCost: 260,
    tier: 'uncommon',
    category: 'music',
    animationType: 'burst',
    color: 'from-yellow-500 to-amber-700',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'music_009',
    name: 'Grand Piano',
    emoji: '🎹',
    coinCost: 800,
    tier: 'rare',
    category: 'music',
    animationType: 'spin',
    color: 'from-slate-700 to-gray-900',
    rarity: 'rare',
  },
  {
    id: 'music_010',
    name: 'Harp',
    emoji: '🎻✨',
    coinCost: 1000,
    tier: 'rare',
    category: 'music',
    animationType: 'spin',
    color: 'from-yellow-300 to-amber-500',
    rarity: 'rare',
  },
  {
    id: 'music_011',
    name: 'DJ Set',
    emoji: '🎛️🎶',
    coinCost: 1500,
    tier: 'rare',
    category: 'music',
    animationType: 'spin',
    color: 'from-blue-400 to-violet-600',
    rarity: 'rare',
  },

  // epic
  {
    id: 'music_012',
    name: 'Concert',
    emoji: '🎤🌟',
    coinCost: 5000,
    tier: 'epic',
    category: 'music',
    animationType: 'explosion',
    color: 'from-violet-500 to-pink-700',
    rarity: 'epic',
  },
  {
    id: 'music_013',
    name: 'Rock Stage',
    emoji: '🎸🔥🥁',
    coinCost: 7000,
    tier: 'epic',
    category: 'music',
    animationType: 'explosion',
    color: 'from-red-500 to-orange-700',
    rarity: 'epic',
  },
  {
    id: 'music_014',
    name: 'Symphony Hall',
    emoji: '🎻🏛️',
    coinCost: 9000,
    tier: 'epic',
    category: 'music',
    animationType: 'explosion',
    color: 'from-amber-400 to-stone-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'music_015',
    name: 'World Tour',
    emoji: '✈️🎤🌍',
    coinCost: 15000,
    tier: 'legendary',
    category: 'music',
    animationType: 'fullscreen',
    color: 'from-pink-500 via-violet-500 to-indigo-600',
    rarity: 'legendary',
  },
  {
    id: 'music_016',
    name: 'Platinum Record',
    emoji: '💿🌟🏆',
    coinCost: 35000,
    tier: 'legendary',
    category: 'music',
    animationType: 'legendary',
    color: 'from-slate-300 via-blue-400 to-violet-600',
    rarity: 'legendary',
  },
  {
    id: 'music_017',
    name: 'Music Legend',
    emoji: '🎸👑🌟⚡',
    coinCost: 77777,
    tier: 'legendary',
    category: 'music',
    animationType: 'legendary',
    color: 'from-yellow-300 via-amber-400 to-red-600',
    rarity: 'legendary',
  },
  {
    id: 'music_018',
    name: 'Hall of Fame',
    emoji: '🏆🎵💫🌟',
    coinCost: 99999,
    tier: 'legendary',
    category: 'music',
    animationType: 'legendary',
    color: 'from-amber-300 via-yellow-500 to-orange-600',
    rarity: 'legendary',
  },

  // =========================================================================
  // FOOD — 17 gifts
  // =========================================================================

  // common
  {
    id: 'food_001',
    name: 'Strawberry',
    emoji: '🍓',
    coinCost: 2,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-red-400 to-rose-500',
    rarity: 'common',
  },
  {
    id: 'food_002',
    name: 'Lollipop',
    emoji: '🍭',
    coinCost: 6,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-pink-400 to-fuchsia-500',
    rarity: 'common',
  },
  {
    id: 'food_003',
    name: 'Cookie',
    emoji: '🍪',
    coinCost: 10,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-amber-400 to-orange-500',
    rarity: 'common',
  },
  {
    id: 'food_004',
    name: 'Ice Cream',
    emoji: '🍦',
    coinCost: 18,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-pink-200 to-rose-300',
    rarity: 'common',
  },
  {
    id: 'food_005',
    name: 'Cake',
    emoji: '🎂',
    coinCost: 30,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-pink-300 to-rose-500',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'food_006',
    name: 'Macarons',
    emoji: '🍬✨',
    coinCost: 65,
    tier: 'uncommon',
    category: 'food',
    animationType: 'burst',
    color: 'from-pink-300 to-violet-400',
    rarity: 'uncommon',
  },
  {
    id: 'food_007',
    name: 'Champagne',
    emoji: '🥂',
    coinCost: 150,
    tier: 'uncommon',
    category: 'food',
    animationType: 'burst',
    color: 'from-yellow-300 to-amber-500',
    rarity: 'uncommon',
  },
  {
    id: 'food_008',
    name: 'Sushi Platter',
    emoji: '🍣🍱',
    coinCost: 220,
    tier: 'uncommon',
    category: 'food',
    animationType: 'burst',
    color: 'from-red-300 to-rose-500',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'food_009',
    name: 'Truffle',
    emoji: '🍄🖤',
    coinCost: 1000,
    tier: 'rare',
    category: 'food',
    animationType: 'spin',
    color: 'from-stone-600 to-slate-700',
    rarity: 'rare',
  },
  {
    id: 'food_010',
    name: 'Caviar',
    emoji: '🫧🥄',
    coinCost: 1400,
    tier: 'rare',
    category: 'food',
    animationType: 'spin',
    color: 'from-slate-600 to-gray-800',
    rarity: 'rare',
  },
  {
    id: 'food_011',
    name: 'Michelin Dinner',
    emoji: '🍽️⭐',
    coinCost: 1800,
    tier: 'rare',
    category: 'food',
    animationType: 'spin',
    color: 'from-amber-500 to-red-600',
    rarity: 'rare',
  },

  // epic
  {
    id: 'food_012',
    name: 'Golden Feast',
    emoji: '🍾🥂🍽️',
    coinCost: 4000,
    tier: 'epic',
    category: 'food',
    animationType: 'explosion',
    color: 'from-yellow-400 to-amber-700',
    rarity: 'epic',
  },
  {
    id: 'food_013',
    name: 'Private Banquet',
    emoji: '🏰🍷🕯️',
    coinCost: 7000,
    tier: 'epic',
    category: 'food',
    animationType: 'explosion',
    color: 'from-red-600 to-stone-800',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'food_014',
    name: 'Royal Banquet',
    emoji: '👑🍾🍽️✨',
    coinCost: 20000,
    tier: 'legendary',
    category: 'food',
    animationType: 'fullscreen',
    color: 'from-amber-400 via-yellow-500 to-orange-700',
    rarity: 'legendary',
  },
  {
    id: 'food_015',
    name: 'Ambrosia',
    emoji: '✨🍯🌺🥂',
    coinCost: 55000,
    tier: 'legendary',
    category: 'food',
    animationType: 'legendary',
    color: 'from-yellow-300 via-amber-400 to-rose-500',
    rarity: 'legendary',
  },
  {
    id: 'food_016',
    name: 'God\'s Table',
    emoji: '⚡🍽️👑🌟',
    coinCost: 99000,
    tier: 'legendary',
    category: 'food',
    animationType: 'legendary',
    color: 'from-amber-300 via-yellow-300 to-white',
    rarity: 'legendary',
  },
  {
    id: 'food_017',
    name: 'Sunrise Brunch',
    emoji: '☀️🥐🍊',
    coinCost: 45,
    tier: 'common',
    category: 'food',
    animationType: 'toast',
    color: 'from-orange-300 to-yellow-400',
    rarity: 'common',
  },

  // =========================================================================
  // NATURE — 18 gifts
  // =========================================================================

  // common
  {
    id: 'nature_001',
    name: 'Leaf',
    emoji: '🍀',
    coinCost: 1,
    tier: 'common',
    category: 'nature',
    animationType: 'toast',
    color: 'from-green-400 to-emerald-500',
    rarity: 'common',
  },
  {
    id: 'nature_002',
    name: 'Sunflower',
    emoji: '🌻',
    coinCost: 8,
    tier: 'common',
    category: 'nature',
    animationType: 'toast',
    color: 'from-yellow-400 to-amber-500',
    rarity: 'common',
  },
  {
    id: 'nature_003',
    name: 'Snowflake',
    emoji: '❄️',
    coinCost: 12,
    tier: 'common',
    category: 'nature',
    animationType: 'toast',
    color: 'from-blue-200 to-cyan-300',
    rarity: 'common',
  },
  {
    id: 'nature_004',
    name: 'Cherry Blossom',
    emoji: '🌸',
    coinCost: 22,
    tier: 'common',
    category: 'nature',
    animationType: 'toast',
    color: 'from-pink-200 to-rose-300',
    rarity: 'common',
  },
  {
    id: 'nature_005',
    name: 'Full Moon',
    emoji: '🌕',
    coinCost: 38,
    tier: 'common',
    category: 'nature',
    animationType: 'toast',
    color: 'from-yellow-200 to-amber-300',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'nature_006',
    name: 'Rainbow',
    emoji: '🌈',
    coinCost: 200,
    tier: 'uncommon',
    category: 'nature',
    animationType: 'burst',
    color: 'from-red-400 via-yellow-400 to-blue-500',
    rarity: 'uncommon',
  },
  {
    id: 'nature_007',
    name: 'Waterfall',
    emoji: '🌊💧',
    coinCost: 120,
    tier: 'uncommon',
    category: 'nature',
    animationType: 'burst',
    color: 'from-blue-400 to-cyan-600',
    rarity: 'uncommon',
  },
  {
    id: 'nature_008',
    name: 'Volcano',
    emoji: '🌋🔥',
    coinCost: 280,
    tier: 'uncommon',
    category: 'nature',
    animationType: 'burst',
    color: 'from-orange-500 to-red-700',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'nature_009',
    name: 'Shooting Star',
    emoji: '🌠',
    coinCost: 450,
    tier: 'rare',
    category: 'nature',
    animationType: 'spin',
    color: 'from-yellow-300 to-indigo-500',
    rarity: 'rare',
  },
  {
    id: 'nature_010',
    name: 'Comet',
    emoji: '☄️',
    coinCost: 900,
    tier: 'rare',
    category: 'nature',
    animationType: 'spin',
    color: 'from-blue-400 to-indigo-700',
    rarity: 'rare',
  },
  {
    id: 'nature_011',
    name: 'Solar Eclipse',
    emoji: '🌑🌟',
    coinCost: 1600,
    tier: 'rare',
    category: 'nature',
    animationType: 'spin',
    color: 'from-slate-800 to-amber-500',
    rarity: 'rare',
  },

  // epic
  {
    id: 'nature_012',
    name: 'Aurora',
    emoji: '🌌🌈',
    coinCost: 2000,
    tier: 'epic',
    category: 'nature',
    animationType: 'explosion',
    color: 'from-green-400 via-teal-500 to-violet-600',
    rarity: 'epic',
  },
  {
    id: 'nature_013',
    name: 'Supernova',
    emoji: '💥⭐',
    coinCost: 4500,
    tier: 'epic',
    category: 'nature',
    animationType: 'explosion',
    color: 'from-yellow-300 via-orange-500 to-red-700',
    rarity: 'epic',
  },
  {
    id: 'nature_014',
    name: 'Black Hole',
    emoji: '🕳️🌌',
    coinCost: 8000,
    tier: 'epic',
    category: 'nature',
    animationType: 'explosion',
    color: 'from-slate-900 via-indigo-900 to-purple-900',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'nature_015',
    name: 'Galaxy',
    emoji: '🌌🌠✨',
    coinCost: 30000,
    tier: 'legendary',
    category: 'nature',
    animationType: 'fullscreen',
    color: 'from-indigo-700 via-purple-600 to-pink-500',
    rarity: 'legendary',
  },
  {
    id: 'nature_016',
    name: 'Universe',
    emoji: '🌍🌙⭐🌌',
    coinCost: 60000,
    tier: 'legendary',
    category: 'nature',
    animationType: 'legendary',
    color: 'from-slate-900 via-indigo-800 to-violet-700',
    rarity: 'legendary',
  },
  {
    id: 'nature_017',
    name: 'Big Bang',
    emoji: '💥🌌✨🌍',
    coinCost: 99999,
    tier: 'legendary',
    category: 'nature',
    animationType: 'legendary',
    color: 'from-white via-yellow-300 to-indigo-900',
    rarity: 'legendary',
  },
  {
    id: 'nature_018',
    name: 'Thunder Storm',
    emoji: '⛈️⚡',
    coinCost: 70,
    tier: 'uncommon',
    category: 'nature',
    animationType: 'burst',
    color: 'from-slate-600 to-indigo-700',
    rarity: 'uncommon',
  },

  // =========================================================================
  // GAMING — 17 gifts
  // =========================================================================

  // common
  {
    id: 'gaming_001',
    name: 'Pixel Heart',
    emoji: '👾',
    coinCost: 5,
    tier: 'common',
    category: 'gaming',
    animationType: 'toast',
    color: 'from-green-400 to-emerald-500',
    rarity: 'common',
  },
  {
    id: 'gaming_002',
    name: 'Joystick',
    emoji: '🕹️',
    coinCost: 12,
    tier: 'common',
    category: 'gaming',
    animationType: 'toast',
    color: 'from-slate-400 to-gray-600',
    rarity: 'common',
  },
  {
    id: 'gaming_003',
    name: 'Game Controller',
    emoji: '🎮',
    coinCost: 25,
    tier: 'common',
    category: 'gaming',
    animationType: 'toast',
    color: 'from-indigo-400 to-blue-500',
    rarity: 'common',
  },
  {
    id: 'gaming_004',
    name: 'Dice',
    emoji: '🎲',
    coinCost: 8,
    tier: 'common',
    category: 'gaming',
    animationType: 'toast',
    color: 'from-slate-300 to-slate-500',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'gaming_005',
    name: 'Sword',
    emoji: '🗡️',
    coinCost: 70,
    tier: 'uncommon',
    category: 'gaming',
    animationType: 'burst',
    color: 'from-slate-400 to-blue-500',
    rarity: 'uncommon',
  },
  {
    id: 'gaming_006',
    name: 'Shield',
    emoji: '🛡️',
    coinCost: 110,
    tier: 'uncommon',
    category: 'gaming',
    animationType: 'burst',
    color: 'from-blue-400 to-indigo-600',
    rarity: 'uncommon',
  },
  {
    id: 'gaming_007',
    name: 'Potion',
    emoji: '🧪❤️',
    coinCost: 180,
    tier: 'uncommon',
    category: 'gaming',
    animationType: 'burst',
    color: 'from-red-400 to-rose-600',
    rarity: 'uncommon',
  },
  {
    id: 'gaming_008',
    name: 'Power-Up',
    emoji: '⭐🎮',
    coinCost: 250,
    tier: 'uncommon',
    category: 'gaming',
    animationType: 'burst',
    color: 'from-yellow-400 to-amber-600',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'gaming_009',
    name: 'Trophy',
    emoji: '🏆',
    coinCost: 300,
    tier: 'rare',
    category: 'gaming',
    animationType: 'spin',
    color: 'from-yellow-400 to-amber-600',
    rarity: 'rare',
  },
  {
    id: 'gaming_010',
    name: 'Legendary Sword',
    emoji: '⚔️🌟',
    coinCost: 750,
    tier: 'rare',
    category: 'gaming',
    animationType: 'spin',
    color: 'from-blue-400 to-violet-600',
    rarity: 'rare',
  },
  {
    id: 'gaming_011',
    name: 'Magic Bow',
    emoji: '🏹✨',
    coinCost: 1200,
    tier: 'rare',
    category: 'gaming',
    animationType: 'spin',
    color: 'from-green-400 to-teal-600',
    rarity: 'rare',
  },
  {
    id: 'gaming_012',
    name: 'Boss Raid',
    emoji: '💀⚔️',
    coinCost: 1800,
    tier: 'rare',
    category: 'gaming',
    animationType: 'spin',
    color: 'from-red-500 to-slate-700',
    rarity: 'rare',
  },

  // epic
  {
    id: 'gaming_013',
    name: 'Crown',
    emoji: '👑🎮',
    coinCost: 2500,
    tier: 'epic',
    category: 'gaming',
    animationType: 'explosion',
    color: 'from-yellow-400 to-amber-700',
    rarity: 'epic',
  },
  {
    id: 'gaming_014',
    name: 'Final Boss',
    emoji: '👹💥',
    coinCost: 6000,
    tier: 'epic',
    category: 'gaming',
    animationType: 'explosion',
    color: 'from-red-600 to-orange-800',
    rarity: 'epic',
  },
  {
    id: 'gaming_015',
    name: 'Server Crash',
    emoji: '💻🔥',
    coinCost: 8500,
    tier: 'epic',
    category: 'gaming',
    animationType: 'explosion',
    color: 'from-orange-500 to-red-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'gaming_016',
    name: 'Legend Status',
    emoji: '🌟👑🎮',
    coinCost: 99999,
    tier: 'legendary',
    category: 'gaming',
    animationType: 'legendary',
    color: 'from-amber-300 via-yellow-400 to-orange-600',
    rarity: 'legendary',
  },
  {
    id: 'gaming_017',
    name: 'World First',
    emoji: '🌍🏆🔥✨',
    coinCost: 50000,
    tier: 'legendary',
    category: 'gaming',
    animationType: 'legendary',
    color: 'from-yellow-300 via-amber-500 to-red-600',
    rarity: 'legendary',
  },

  // =========================================================================
  // SPECIAL — 20 gifts
  // =========================================================================

  // common
  {
    id: 'special_001',
    name: 'Confetti',
    emoji: '🎊',
    coinCost: 4,
    tier: 'common',
    category: 'special',
    animationType: 'toast',
    color: 'from-pink-300 via-yellow-300 to-blue-300',
    rarity: 'common',
  },
  {
    id: 'special_002',
    name: 'Sparkle',
    emoji: '✨',
    coinCost: 9,
    tier: 'common',
    category: 'special',
    animationType: 'toast',
    color: 'from-yellow-300 to-amber-400',
    rarity: 'common',
  },
  {
    id: 'special_003',
    name: 'Party Popper',
    emoji: '🎉',
    coinCost: 16,
    tier: 'common',
    category: 'special',
    animationType: 'toast',
    color: 'from-fuchsia-400 to-pink-500',
    rarity: 'common',
  },
  {
    id: 'special_004',
    name: 'Shooting Clap',
    emoji: '👏',
    coinCost: 30,
    tier: 'common',
    category: 'special',
    animationType: 'toast',
    color: 'from-amber-300 to-yellow-500',
    rarity: 'common',
  },
  {
    id: 'special_005',
    name: 'Rainbow Flag',
    emoji: '🏳️‍🌈',
    coinCost: 42,
    tier: 'common',
    category: 'special',
    animationType: 'toast',
    color: 'from-red-400 via-yellow-400 to-violet-500',
    rarity: 'common',
  },

  // uncommon
  {
    id: 'special_006',
    name: 'Firework',
    emoji: '🎆',
    coinCost: 60,
    tier: 'uncommon',
    category: 'special',
    animationType: 'burst',
    color: 'from-orange-400 via-red-500 to-violet-600',
    rarity: 'uncommon',
  },
  {
    id: 'special_007',
    name: 'Hype Train',
    emoji: '🚂💨',
    coinCost: 100,
    tier: 'uncommon',
    category: 'special',
    animationType: 'burst',
    color: 'from-orange-400 to-red-600',
    rarity: 'uncommon',
  },
  {
    id: 'special_008',
    name: 'VIP Pass',
    emoji: '🎫⭐',
    coinCost: 200,
    tier: 'uncommon',
    category: 'special',
    animationType: 'burst',
    color: 'from-violet-500 to-indigo-700',
    rarity: 'uncommon',
  },
  {
    id: 'special_009',
    name: 'Birthday Cake',
    emoji: '🎂🎉',
    coinCost: 280,
    tier: 'uncommon',
    category: 'special',
    animationType: 'burst',
    color: 'from-pink-400 to-rose-600',
    rarity: 'uncommon',
  },

  // rare
  {
    id: 'special_010',
    name: 'Crown of Stars',
    emoji: '👑⭐',
    coinCost: 400,
    tier: 'rare',
    category: 'special',
    animationType: 'spin',
    color: 'from-yellow-300 to-amber-600',
    rarity: 'rare',
  },
  {
    id: 'special_011',
    name: 'Time Capsule',
    emoji: '⏳✨',
    coinCost: 700,
    tier: 'rare',
    category: 'special',
    animationType: 'spin',
    color: 'from-blue-300 to-teal-500',
    rarity: 'rare',
  },
  {
    id: 'special_012',
    name: 'Cosmic Drift',
    emoji: '🪐💫',
    coinCost: 1000,
    tier: 'rare',
    category: 'special',
    animationType: 'spin',
    color: 'from-indigo-400 to-violet-700',
    rarity: 'rare',
  },
  {
    id: 'special_013',
    name: 'Neon Sign',
    emoji: '💡🎭',
    coinCost: 1700,
    tier: 'rare',
    category: 'special',
    animationType: 'spin',
    color: 'from-fuchsia-400 to-pink-600',
    rarity: 'rare',
  },

  // epic
  {
    id: 'special_014',
    name: 'Live Moment',
    emoji: '📸🌟',
    coinCost: 2500,
    tier: 'epic',
    category: 'special',
    animationType: 'explosion',
    color: 'from-pink-500 to-orange-600',
    rarity: 'epic',
  },
  {
    id: 'special_015',
    name: 'Gold Spotlight',
    emoji: '🔦🌟',
    coinCost: 4500,
    tier: 'epic',
    category: 'special',
    animationType: 'explosion',
    color: 'from-yellow-400 to-amber-700',
    rarity: 'epic',
  },
  {
    id: 'special_016',
    name: 'Viral Moment',
    emoji: '📱🔥🌍',
    coinCost: 7500,
    tier: 'epic',
    category: 'special',
    animationType: 'explosion',
    color: 'from-orange-500 to-red-700',
    rarity: 'epic',
  },
  {
    id: 'special_017',
    name: 'Time Freeze',
    emoji: '⏸️✨',
    coinCost: 9500,
    tier: 'epic',
    category: 'special',
    animationType: 'explosion',
    color: 'from-cyan-400 to-blue-700',
    rarity: 'epic',
  },

  // legendary
  {
    id: 'special_018',
    name: 'Hall of Fame',
    emoji: '🏛️🌟👑',
    coinCost: 10000,
    tier: 'legendary',
    category: 'special',
    animationType: 'fullscreen',
    color: 'from-amber-300 via-yellow-400 to-white',
    rarity: 'legendary',
  },
  {
    id: 'special_019',
    name: 'Chosen One',
    emoji: '🌟☀️🔮👑',
    coinCost: 55555,
    tier: 'legendary',
    category: 'special',
    animationType: 'legendary',
    color: 'from-white via-yellow-300 to-amber-600',
    rarity: 'legendary',
  },
  {
    id: 'special_020',
    name: 'Discordium God',
    emoji: '⚡🌌👑💎🔥',
    coinCost: 99999,
    tier: 'legendary',
    category: 'special',
    animationType: 'legendary',
    color: 'from-violet-500 via-fuchsia-500 to-pink-500',
    rarity: 'legendary',
  },
];

// ---------------------------------------------------------------------------
// HELPER FUNCTIONS
// ---------------------------------------------------------------------------

/**
 * Returns all gifts belonging to a given category.
 */
export function getGiftsByCategory(category: GiftCategory): Gift[] {
  return GIFTS.filter((g) => g.category === category);
}

/**
 * Returns all gifts belonging to a given tier, sorted by coinCost ascending.
 */
export function getGiftsByTier(tier: GiftTier): Gift[] {
  return GIFTS.filter((g) => g.tier === tier).sort((a, b) => a.coinCost - b.coinCost);
}

/**
 * Formats a coin count into a compact human-readable string.
 *
 * Examples:
 *   1      → "1"
 *   999    → "999"
 *   1000   → "1K"
 *   1500   → "1.5K"
 *   99999  → "99.9K"
 *   100000 → "100K"
 */
export function formatCoinCost(n: number): string {
  if (n < 1000) return String(n);
  const k = n / 1000;
  // Keep at most one decimal place, strip trailing zero
  const formatted = k % 1 === 0 ? `${k}K` : `${k.toFixed(1)}K`;
  return formatted;
}
